#CREANDO VECTORES PARA DATOS ESTUDIANTES

```{r}
student_1 <- c(50.4,62.3,92.1,77.6,T)
student_2 <- c(41.7,87.9,75.3,72.4,F)
student_3 <- c(30.3,67.8,69.3,71.2,F)
student_4 <- c(65.4,85.1,92.3,96.8,T)
student_5 <- c(70.4,88.2,95.2,90.7,T)

students_vector <- c(student_1,student_2,student_3,student_4,student_5)

students_matrix <- matrix(students_vector,byrow=T,nrow=5)
students_matrix

```

#NOMBRANDO MATRICES
```{r}
name_students <- c("Lily Brown","Davis Moore","Susan Taylor","Mike Jones","Tom Hill")
name_couses_legal_age <- c("TIC","Accounting","Psychology","Ethics","Legal_Age")

colnames(students_matrix)<- name_couses_legal_age
rownames(students_matrix)<- name_students
students_matrix

```
#Sumando filas y cbind
```{r}

total_grade_student <- .rowSums(students_matrix,5,4,na.rm=T)
total_grade_student
result_students <- cbind(students_matrix,total_grade_student)
result_students


```
#SELECCIONANDO ELEMENTOS DE UNA MATRIZ
```{r}
f1 <- result_students[1,]
f3 <- result_students[3,]
f5 <- result_students[5,]
c2 <- result_students[,2]
c4 <- result_students[0,4]
selected_elements <- matrix(c(f1,f3,f5,c2,c4))
selected_elements
```
#DATA FRAMES
```{r}
students_grades_df <- data.frame(result_students)
students_grades_df
subset(students_grades_df, subset=Accounting>80 & Legal_Age>0 ,select=c("Accounting","Legal_Age"))


```
#FUNCIONES CONDICIONALES Y BUCLES
```{r}
students_projection1_1 <- function(student,materia){
  if (student=="Lily Brown" & materia=="TIC"){
    if(students_grades_df[1,1]>=61){
      print("Student Approved")
    } else if (students_grades_df[1,1]<61 & students_grades_df[1,1]>45){
      print("Student may be approved")
    } else {
      print("Student at risk")
    }
  }
}

students_projection1_2 <- function(student,materia){
  if (student=="Lily Brown" & materia=="Accounting"){
    if(students_grades_df[1,2]>=61){
      print("Student Approved")
    } else if (students_grades_df[1,2]<61 & students_grades_df[1,2]>45){
      print("Student may be approved")
    } else {
      print("Student at risk")
    }
  }
}

students_projection1_3 <- function(student,materia){
  if (student=="Lily Brown" & materia=="Pysichology"){
    if(students_grades_df[1,3]>=61){
      print("Student Approved")
    } else if (students_grades_df[1,3]<61 & students_grades_df[1,3]>45){
      print("Student may be approved")
    } else {
      print("Student at risk")
    }
  }
}

students_projection1_4 <- function(student,materia){
  if (student=="Lily Brown" & materia=="Ethics"){
    if(students_grades_df[1,4]>=61){
      print("Student Approved")
    } else if (students_grades_df[1,4]<61 & students_grades_df[1,4]>45){
      print("Student may be approved")
    } else {
      print("Student at risk")
    }
  }
}



students_projection2_1 <- function(student,materia){
  if (student=="Davis Moore" & materia=="TIC"){
    if(students_grades_df[2,1]>=61){
      print("Student Approved")
    } else if (students_grades_df[2,1]<61 & students_grades_df[2,1]>45){
      print("Student may be approved")
    } else {
      print("Student at risk")
    }
  }
}

students_projection2_2 <- function(student,materia){
  if (student=="Davis Moore" & materia=="Accounting"){
    if(students_grades_df[2,2]>=61){
      print("Student Approved")
    } else if (students_grades_df[2,2]<61 & students_grades_df[2,2]>45){
      print("Student may be approved")
    } else {
      print("Student at risk")
    }
  }
}

students_projection2_3 <- function(student,materia){
  if (student=="Davis Moore" & materia=="Pysichology"){
    if(students_grades_df[3,3]>=61){
      print("Student Approved")
    } else if (students_grades_df[3,3]<61 & students_grades_df[3,3]>45){
      print("Student may be approved")
    } else {
      print("Student at risk")
    }
  }
}

students_projection2_4 <- function(student,materia){
  if (student=="Davis Moore" & materia=="Ethics"){
    if(students_grades_df[4,4]>=61){
      print("Student Approved")
    } else if (students_grades_df[4,4]<61 & students_grades_df[4,4]>45){
      print("Student may be approved")
    } else {
      print("Student at risk")
    }
  }
}

students_projection3_1 <- function(student,materia){
  if (student=="Susan Taylor" & materia=="TIC"){
    if(students_grades_df[3,1]>=61){
      print("Student Approved")
    } else if (students_grades_df[3,1]<61 & students_grades_df[3,1]>45){
      print("Student may be approved")
    } else {
      print("Student at risk")
    }
  }
}

students_projection3_2 <- function(student,materia){
  if (student=="Susan Taylor" & materia=="Accounting"){
    if(students_grades_df[3,2]>=61){
      print("Student Approved")
    } else if (students_grades_df[3,2]<61 & students_grades_df[3,2]>45){
      print("Student may be approved")
    } else {
      print("Student at risk")
    }
  }
}

students_projection3_3 <- function(student,materia){
  if (student=="Susan Taylor" & materia=="Pysichology"){
    if(students_grades_df[3,3]>=61){
      print("Student Approved")
    } else if (students_grades_df[3,3]<61 & students_grades_df[3,3]>45){
      print("Student may be approved")
    } else {
      print("Student at risk")
    }
  }
}

students_projection3_4 <- function(student,materia){
  if (student=="Susan Taylor" & materia=="Ethics"){
    if(students_grades_df[3,4]>=61){
      print("Student Approved")
    } else if (students_grades_df[3,4]<61 & students_grades_df[3,4]>45){
      print("Student may be approved")
    } else {
      print("Student at risk")
    }
  }
}



students_projection4_1 <- function(student,materia){
  if (student=="Mike Jones" & materia=="TIC"){
    if(students_grades_df[4,1]>=61){
      print("Student Approved")
    } else if (students_grades_df[4,1]<61 & students_grades_df[4,1]>45){
      print("Student may be approved")
    } else {
      print("Student at risk")
    }
  }
}

students_projection4_2 <- function(student,materia){
  if (student=="Mike Jones" & materia=="Accounting"){
    if(students_grades_df[4,2]>=61){
      print("Student Approved")
    } else if (students_grades_df[4,2]<61 & students_grades_df[4,2]>45){
      print("Student may be approved")
    } else {
      print("Student at risk")
    }
  }
}

students_projection4_3 <- function(student,materia){
  if (student=="Mike Jones" & materia=="Pysichology"){
    if(students_grades_df[4,3]>=61){
      print("Student Approved")
    } else if (students_grades_df[4,3]<61 & students_grades_df[4,3]>45){
      print("Student may be approved")
    } else {
      print("Student at risk")
    }
  }
}

students_projection4_4 <- function(student,materia){
  if (student=="Mike Jones" & materia=="Ethics"){
    if(students_grades_df[4,4]>=61){
      print("Student Approved")
    } else if (students_grades_df[4,4]<61 & students_grades_df[4,4]>45){
      print("Student may be approved")
    } else {
      print("Student at risk")
    }
  }
}


students_projection5_1 <- function(student,materia){
  if (student=="Tom Hill" & materia=="TIC"){
    if(students_grades_df[5,1]>=61){
      print("Student Approved")
    } else if (students_grades_df[5,1]<61 & students_grades_df[5,1]>45){
      print("Student may be approved")
    } else {
      print("Student at risk")
    }
  }
}

students_projection5_2 <- function(student,materia){
  if (student=="Tom Hill" & materia=="Accounting"){
    if(students_grades_df[5,2]>=61){
      print("Student Approved")
    } else if (students_grades_df[5,2]<61 & students_grades_df[5,2]>45){
      print("Student may be approved")
    } else {
      print("Student at risk")
    }
  }
}

students_projection5_3 <- function(student,materia){
  if (student=="Tom Hill" & materia=="Pysichology"){
    if(students_grades_df[5,3]>=61){
      print("Student Approved")
    } else if (students_grades_df[5,3]<61 & students_grades_df[5,3]>45){
      print("Student may be approved")
    } else {
      print("Student at risk")
    }
  }
}

students_projection5_4 <- function(student,materia){
  if (student=="Tom Hill" & materia=="Ethics"){
    if(students_grades_df[5,4]>=61){
      print("Student Approved")
    } else if (students_grades_df[5,4]<61 & students_grades_df[5,4]>45){
      print("Student may be approved")
    } else {
      print("Student at risk")
    }
  }
}

students_projection <- function(S,M){
  if (S=="Lily Brown"& M=="TIC"){
    print(studentsprojection1_1)
  } else if (S=="Lily Brown"& M=="Accountability"){
    print(students_projection1_2("Lily Brown","Accountability"))
  } else if (S=="Lily Brown"& M=="Pysichology"){
    print(students_projection1_3("Lily Brown","Pysichology"))
  } else if (S=="Lily Brown"& M=="Ethics"){
    print(students_projection1_4("DAvis Moore","Ethics"))
  } else if (S=="Lily Brown"& M=="Accountability"){
    print(students_projection2_2("Davis Moore","Accountability"))
  } else if (S=="Lily Brown"& M=="Pysichology"){
    print(students_projection2_3("Davis Moore","Pysichology"))
  } else if (S=="Lily Brown"& M=="Ethics"){
    print(students_projection2_4("Lily Brown","Ethics")) 
}

  
  

```


#INDEX
```{r}
index_education <- function(grade){
  ie=(1+(grade/100))/2
  return(ie)
}

index_education(student_grades_df[1,])
grades<- students_grades_df[,4]+students_grades_df[,3]+ students_grades_df[,1]+students_grades_df[,2]
grades_1 <- sum(grades)
grades_1


all_students_grades <- index_education(grades_1)

all_students_grades
```
#MATH

```{r}
mean_1<- mean(students_grades_df$TIC)
mean_2<- mean(students_grades_df$Accounting)
mean_3<- mean(students_grades_df$Psychology)
mean_4<- mean(students_grades_df$Ethics)
score_mean <- (mean_1+mean_2+mean_3+mean_4)/4
score_mean
```














